version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductOrderDb;User Id=sa;Password=Your_password123;
    ports:
      - "5000:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "docker"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"